# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    - releases/*
    - refs/tags/*

pool:
  vmImage: "Ubuntu-16.04"

steps:
  - script: ansible-galaxy install -p roles -r requirements.yml
    displayName: "Download ansible roles"

  - script: tar cvzf dev-env-$(Build.SourceBranchName).tar.gz *
    displayName: "Package the artifact"

  - task: CopyFiles@2
    inputs:
      Contents: 'dev-env-$(Build.SourceBranchName).tar.gz'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: GithubRelease@0
    displayName: "Create GitHub Release"
    inputs:
      githubConnection: siavashoutadi
      repositoryName: siavashoutadi/dev-env
