- src: siavashoutadi.git
  version: 1.0.0
- src: geerlingguy.repo-epel
  version: 1.2.3
- src: geerlingguy.pip
  version: 1.3.0
- src: gantsign.pyenv
  version: 1.0.0
- src: gantsign.java
  version: 7.1.0
- src: gantsign.maven
  version: 5.3.0
- src: geerlingguy.docker
  version: 2.5.2
- src: gantsign.minikube
  version: 1.7.0
- src: gantsign.visual-studio-code
  version: 6.2.1
- src: gantsign.intellij
  version: 5.5.5
