- src: siavashoutadi.git
  version: 1.0.0
- src: geerlingguy.repo-epel
  version: 1.2.4
- src: geerlingguy.pip
  version: 1.3.0
- src: gantsign.pyenv
  version: 1.0.0
- src: gantsign.java
  version: 8.1.1
- src: gantsign.maven
  version: 5.4.2
- src: geerlingguy.docker
  version: 2.6.0
- src: gantsign.minikube
  version: 1.14.1
- src: gantsign.visual-studio-code
  version: 6.3.1
- src: gantsign.intellij
  version: 5.9.1
- src: gantsign.golang
  version: 2.2.5
- src: geerlingguy.ruby
  version: 2.6.0
- src: gantsign.helm
  version: 2.0.2
- src: gantsign.ctop
  version: 1.1.1
