- src: siavashoutadi.git
  version: 1.0.0
- src: nephelaiio.devtools
  version: 2.0.0
- src: geerlingguy.repo-epel
  version: 1.2.3
- src: geerlingguy.pip
  version: 1.3.0
- src: gantsign.pyenv
  version: 1.0.0
- src: gantsign.java
  version: 7.2.0
- src: gantsign.maven
  version: 5.3.0
- src: geerlingguy.docker
  version: 2.5.2
- src: gantsign.minikube
  version: 1.8.0
- src: gantsign.visual-studio-code
  version: 6.2.1
- src: gantsign.intellij
  version: 5.6.1
- src: gantsign.golang
  version: 2.1.4
- src: geerlingguy.ruby
  version: 2.6.0
- src: gantsign.helm
  version: 1.4.1
- src: gantsign.ctop
  version: 1.1.0
