---
- name: Setup a development environment
  hosts: dev_env
  become: yes
  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - role: siavashoutadi.git
    - role: geerlingguy.pip
    - role: gantsign.pyenv
    - role: geerlingguy.ruby
      tags:
        - ruby
    - role: gantsign.java
    - role: gantsign.maven
    - role: geerlingguy.docker
    - role: gantsign.minikube
    - role: gantsign.visual-studio-code
      vars:
        users: "{{ visual_studio_code_users | default([]) }}"
    - role: gantsign.intellij
      vars:
        users: "{{ intellij_users | default([]) }}"
    - role: gantsign.golang
    - role: geerlingguy.nodejs
    - role: devoperate.virtualbox
      tags:
        - virtualbox
    - role: devoperate.vagrant
      tags:
        - vagrant
    - role: devoperate.google_chrome
      tags:
        - google_chrome
