---
- name: Setup a development environment
  hosts: dev_env
  become: yes
  roles:
    - role: geerlingguy.repo-epel
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      tags:
        - epel
    - role: nephelaiio.devtools
      tags:
        - build_tools
    - role: siavashoutadi.git
      tags:
        - git
    - role: geerlingguy.pip
      tags:
        - pip
    - role: gantsign.pyenv
      tags:
        - pyenv
    - role: geerlingguy.ruby
      vars:
        ruby_packages:
          - ruby
          - ruby-devel
          - "@development-tools"
      when: ansible_distribution == 'Fedora'
      tags:
        - ruby
    - role: geerlingguy.ruby
      when: ansible_distribution != 'Fedora'
      tags:
        - ruby
    - role: gantsign.java
      tags:
        - java
    - role: gantsign.maven
      tags:
        - maven
    - role: geerlingguy.docker
      tags:
        - docker
    - role: gantsign.ctop
      tags:
        - ctop
    - role: gantsign.minikube
      tags:
        - minikube
    - role: devoperate.kubectl
      tags:
        - kubectl
    - role: gantsign.helm
      tags:
        - helm
    - role: gantsign.visual-studio-code
      vars:
        users: "{{ visual_studio_code_users | default([]) }}"
      tags:
        - vscode
    - role: gantsign.intellij
      vars:
        users: "{{ intellij_users | default([]) }}"
      tags:
        - intellij
    - role: gantsign.golang
      tags:
        - golang
    - role: devoperate.nodejs
      tags:
        - nodejs
    - role: devoperate.virtualbox
      tags:
        - virtualbox
    - role: devoperate.vagrant
      tags:
        - vagrant
    - role: devoperate.google_chrome
      tags:
        - google_chrome

- name: Add bash completion for kubectl
  hosts: dev_env
  become: yes
  tasks:
    - shell: kubectl completion bash >/etc/bash_completion.d/kubectl
      tags:
        - kubectl
      changed_when: false

- name: Install extra packages
  hosts: dev_env
  become: yes
  tasks:
    - package:
        name: "{{ dev_env_packages | default([])}}"
        state: present
      tags:
        - extra_packages
