---
- name: Setup a development environment
  hosts: dev_env
  become: yes
  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - role: siavashoutadi.git
    - role: geerlingguy.pip
    - role: gantsign.pyenv
    - role: gantsign.java
